name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.1.2
       name: Checkout do repositorio 
     - name: Autenticação no Docker
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_PWD }}
     - name: Construção da imagem Docker
       with:
         context: ./src
         file: ./src/Dockeerfile
         push: true
         tags: |
           lfogaca34/devops4devs-news:latest
           lfogaca34/devops4devs-news:${(github.run_number}
           
       run: echo "Docker Build"
     - name: "Publicar a imagem no Docker Hub"
       run: echo "Docker push"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com o Kubernetes
        run: echo "Configuração do Kubeconfig"
      - name: Executar o deploy
        run: echo "Kubectl apply"
 
